package com.example.bgg.resources

import com.example.bgg.dto.GameDto

fun mechanicsMap() = mapOf(
    "Acting" to "n1GtBt35Rd",
    "Action / Movement Programming" to "PGjmKGi26h",
    "Action Point Allowance System" to "oeg6wN9Eoc",
    "Action Selection" to "Bc7R8pLoGk",
    "Area Control" to "05zCZoLvQJ",
    "Area Enclosure" to "3te2oybNR4",
    "Area Movement" to "bgGxE0pI2B",
    "Asymmetric" to "amcImLdOmD",
    "Auction" to "AZxlPpi5oq",
    "Betting" to "3tuJiW3pps",
    "Bluffing" to "ZX3hYcF9H7",
    "Building" to "UEzHyBWtz8",
    "Campaign" to "xuphiSlrxI",
    "Card Drafting" to "iWODHwRGuU",
    "Card Game" to "ebJKldFVeS",
    "Card Placement" to "ngCSHHk0H2",
    "Chit-Pull System" to "Gan96fffLL",
    "Comodity Speculation" to "K0ykGhTMa8",
    "Confusion" to "AAi6B8NLaV",
    "Conversation" to "hwyCo1W0hi",
    "Cooperative" to "33UT4gTFqy",
    "Cooperative Play" to "9mNukNBxfZ",
    "Crayon Rail System" to "xVDf5dmJts",
    "Currency" to "9y0yU5xWRU",
    "D6 RPG" to "kZf6CVjtq7",
    "Deck Building" to "vZsDDAdOoe",
    "Deduction" to "GsNGxZFNCK",
    "Dexterity" to "5kvyChnWuO",
    "Dice Building" to "lVSHu9efHv",
    "Dice Movement" to "zw4KMn5rcD",
    "Dice Rolling" to "R0bGq4cAl4",
    "Drafting" to "wV5peB05xs",
    "Drawing" to "KfTS5BwIsu",
    "Drinking" to "Ouo00D4ka7",
    "Engine Building" to "yu3eas6v7A",
    "Euro Game" to "hUn7uJHrYm",
    "Fighting" to "kS8npG0jl8",
    "Flicking" to "S0O9ucexPS",
    "Grid Movement" to "qu5BcGjAzk",
    "Hand Management" to "WPytek5P8l",
    "Hand-Eye Coordination" to "i3xnwJ7VPV",
    "Hex and Counter" to "6CyVyXRn1C",
    "Hidden Movement" to "aQZ40lKv8O",
    "Hidden Traitor" to "Voqy2dgrIM",
    "Legacy" to "DwmsVEvNVd",
    "Line Drawing" to "MaXzmoZUoX",
    "Live action and Role Playing game (Larp)" to "UaLql58fua",
    "Mancala" to "ar56ACXDNe",
    "Memory" to "r6yIFvyXDD",
    "Modular Board" to "U3zhCQH7Et",
    "Paper and Pencil" to "UHdPUeuqyZ",
    "Partnerships" to "GNtouC8NLm",
    "Party Game" to "3dFd0RwsY4",
    "Pattern Building" to "9YdRn9J9oZ",
    "Pattern Recognition" to "uZJS07nXF5",
    "Pick-up and Deliver" to "BbTMRkwL0b",
    "Player Elimination" to "BGrhzIN69D",
    "Player vs. Player" to "YyBg5CzHBF",
    "Point to Point Movement" to "MEAoOygZsA",
    "Pool Building" to "ea1eaPBQn8",
    "Press Your Luck" to "hmipYN1R1I",
    "Puzzle" to "24FWssBC3o",
    "Real Time" to "E9VKQ8uMSP",
    "Resource Gathering" to "Rt6V388y6M",
    "Rock-Paper-Scissors" to "j7x8jY4ay2",
    "Role Playing" to "EVeAdboGUA",
    "Role Selection" to "gRlslORtpI",
    "Roll / Spin and Move" to "mGBzR68m8Z",
    "Roll and Write" to "zIPRS41oiN",
    "Rondel" to "FA6HjbhdNW",
    "Route Building" to "asw8k7EIJI",
    "Route/Network Building" to "c6gkRM7rSy",
    "Secret Unit Deployment" to "RwgEONzIzc",
    "Set Collection" to "lA3KUtVFCy",
    "Simulation" to "eRe1jJCBFe",
    "Simultaneous Play" to "DEvPj5twid",
    "Simultaneous action selection" to "za4PP1LH00",
    "Skirmish" to "kuRNhFADjS",
    "Social Deduction" to "x3wVCq1HEP",
    "Stock Holding" to "jbLrZb1xIb",
    "Storytelling" to "GUoWg3Mfh5",
    "Tactical Movement" to "yDlgk7rXno",
    "Tactics" to "jCRze30VP1",
    "Take That" to "T8JEFYwoqy",
    "Teams" to "9jnCsVuRat",
    "Tile Placement" to "8PN2HE86wg",
    "Time Track" to "cXd5KaXXZo",
    "Tower Defense" to "wEBvff5T5c",
    "Trading" to "AVY6EvSQTP",
    "Trick-taking" to "3GSQl800lk",
    "Variable Phase Order" to "zzsE4jtI1b",
    "Variable Player Powers" to "XM2FYZmBHH",
    "Voting" to "JYYdBW6UCE",
    "Wargame" to "yomuPpKFx4",
    "Worker Placement" to "fBOTEBUAmV"
)

fun categoriesMap() = mapOf(
    "4x" to "85OKv8p5Ow",
    "Abstract" to "hBqZ3Ar4RJ",
    "Adventure" to "KUBCKBkGxV",
    "Age of Reason" to "20iDvpbh7A",
    "Alternate History" to "nWDac9tQzt",
    "American West" to "4mOtRRwSoj",
    "Ancient" to "a8NM5cugJX",
    "Animals" to "MWoxgHrOJD",
    "Apocalyptic" to "eFaACC6y2c",
    "Art" to "k0dglq5j6N",
    "Aviation" to "QB4sEpx1Uu",
    "Bluffing" to "PinhJrhnxU",
    "Campaign" to "fW5vusE96B",
    "Card Game" to "eX8uuNlQkQ",
    "Children's Game" to "HKaYVNIxAJ",
    "City Building" to "ODWOjWAJj3",
    "Civil War" to "w8XD66FUZ2",
    "Civilization" to "329DxyFL9D",
    "Collectible Components" to "vXxLT0FDTZ",
    "Comic Book / Strip" to "G5kfqnPBP6",
    "Conversation" to "iTvYWFmD1c",
    "Cooperative" to "ge8pIhEUGE",
    "Cyberpunk" to "Ef4oYLHNhI",
    "Deduction" to "bCBXJy9qDw",
    "Dexterity" to "bKrxqD9mYc",
    "Dice" to "mavSOM8vjH",
    "Dinosaurs" to "UuxiExraPF",
    "Drinking" to "We3MM46qBr",
    "Dungeons & Dragons" to "ZEW7DPFAE6",
    "Economic" to "N0TkEGfEsF",
    "Educational" to "B3NRLMK4xD",
    "Electronic" to "crxgUzJSEz",
    "Environmental" to "gsekjrPJz0",
    "Espionage" to "u5ZiYctU6T",
    "Eurogame" to "h8wfZG0j3I",
    "Expansion" to "v4SfYtS2Lr",
    "Exploration" to "yq6hVlbM2R",
    "Family Game" to "7rV11PKqME",
    "Fan Made" to "ctumBZyj5l",
    "Fantasy" to "ZTneo8TaIO",
    "Farming" to "Wr8uXcoR9p",
    "Fighting" to "upXZ8vNfNO",
    "Fishing" to "zNxFBqBHXA",
    "Flicking" to "3NDxCLUny4",
    "Food" to "YrDuNj8lvr",
    "Gay" to "H9Ef643lYf",
    "Halloween" to "NR0vgCx5R7",
    "Horror" to "cAIkk5aLdQ",
    "Humor" to "TYnxiuiI3X",
    "Industry/Manufacturing" to "zqFmdU4Fp2",
    "Japan" to "R7PTH00PmO",
    "Kickstarter" to "rrvd68LjOR",
    "Legacy" to "XeYUw9159M",
    "Luck" to "nHZiDOXNla",
    "Mafia" to "pIMmuVYnQp",
    "Math" to "POlqwScVxD",
    "Mature / Adult" to "ZhlfIPxYsw",
    "Mecha" to "c1AnMUJrTF",
    "Medical" to "AeWXMxbm91",
    "Medieval" to "QAYkTHK1Dd",
    "Memory" to "AujCle9cUq",
    "Miniatures" to "FC6ElKI9tk",
    "Modern Warfare" to "L6NUwNdblq",
    "Movie Theme" to "TJnR5obHsQ",
    "Movies / TV / Radio theme" to "Sod2YBWMKi",
    "Murder/Mystery" to "Kk70K0524Z",
    "Mythology" to "MHkqIVxwtx",
    "Napoleonic" to "IpcJzp0TVC",
    "Nautical" to "vqZ5XzGWQD",
    "Negotiation" to "jZEDOpx07e",
    "Ninja's" to "mWb5kHTAg1",
    "Ninjas" to "rtslXnT90O",
    "Novel-based" to "dO9HVl2TW7",
    "Party Game" to "X8J7RM6dxX",
    "Pirates" to "9EIayX6n5a",
    "Political" to "TKQncFVX74",
    "Post-Apocalyptic" to "8Z7nWG2kOw",
    "Post-Napoleonic" to "5APB1MWk6X",
    "Prehistoric" to "YyszHun1HP",
    "Print & Play" to "ov6sEmlkiC",
    "Prison Escape" to "dAyk5NtNTV",
    "Puzzle" to "WVMOS3s2pb",
    "Queer" to "c6nnwyDdnl",
    "RPG" to "2Gu62aKdma",
    "Racing" to "tQGLgwdbYH",
    "Real-time" to "PzWI2uaif0",
    "Religious" to "DRqeVkXWqX",
    "Renaissance" to "nuHYRFmMjU",
    "Resource Management" to "zyj9ZK3mHB",
    "Romance" to "E5rYwP0Ybr",
    "Sci-Fi" to "3B3QpKvXD3",
    "Socialite" to "c6ei4hkUxm",
    "Solo / Solitaire" to "VzyslQJGrG",
    "Space Exploration" to "0MdRqhkNpw",
    "Spies/Secret Agents" to "Hc6vcim5DS",
    "Sports" to "hShsL2DktG",
    "Strategy" to "O0ogzwLUe8",
    "Superhero" to "usFW8szGAq",
    "Tech" to "yHTeXNjln0",
    "Territory Building" to "buDTYyPw4D",
    "Theme Park" to "vCzpbYT7RU",
    "Trains" to "JwHcKqxh33",
    "Transportation" to "CWYOF9xu7O",
    "Travel" to "TR4CiP8Huj",
    "Trivia" to "YGHGDjahKY",
    "Video Game Theme" to "djokexoK0U",
    "War" to "ssZjU3HETz",
    "Wargame" to "jX8asGGR6o",
    "Western" to "EHUBCITA3t",
    "Word Game" to "rHvAx4hH2f",
    "World War I" to "wTLJSVEbm6",
    "World War II" to "fl3TogdUzX",
    "World War III" to "OlkGBmu4Va",
    "Zombies" to "FmGV9rVu1c"
)

fun arrayOfGames(): ArrayList<GameDto> =
    arrayListOf(
        GameDto("EL3YmDLY6W",
            "Risk",
            "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254847937-51zyVWbt8aL.jpg",
            "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254847937-51zyVWbt8aL.jpg",
            2,
            6,
            10,
            "<p>Welcome to the world of Risk. It's exciting. It's unpredictable. It’s all about battling your way to global domination, 1 territory at a time. And it's easy to get into the game, fast! In the Risk game, you focus on your strategy. You decide on your tactical scheme. You figure out where to place your troops, and who and where you will attack and how often. Every move is a risk that will bring either victory or defeat. Go for the win!</p> <p>Risk and all related terms are trademarks of Hasbro.</p>",
            "Hasbro Games",
            arrayOf("Hasbro Games"),
            2.092307692307693,
            " ",
            "https://www.boardgameatlas.com/search/game/3IWfKb37mc/7-wonders-catan"
        ),
        GameDto(
            "M7UpZZ00UO",
            "Risk: Legacy",
            "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559253933920-51S19kJh93L.jpg",
            "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559253933920-51S19kJh93L.jpg",
            3,
            5,
            13,
            "    2012 Golden Geek Winner - Most Innovative   \\nHow will you shape your world? \\n \\nIn Risk Legacy, every game you play will change every future game. A decision you make in Game 1 could come back to haunt you in Game 10. The risks you take in Risk Legacy are not like those in any other board game. You and the other players will shape how your world evolves: its history, its cities, even its factions and how they fight. Cards and stickers will come into play. Cards will go out of play forever. You don't forget past betrayals - and neither does the game. Unlock new rules and watch events unfold as you play more games. No two games will EVER be the same. Play your game. Write your history.",
            "Hasbro",
            arrayOf("Hasbro"),
            3.346153846153846,
            " ",
            "https://www.boardgameatlas.com/search/game/3IWfKb37mc/7-wonders-catan"
        ),
        GameDto(
            "fG5Ax8PA7n",
            "Monopoly",
            "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1543278754636",
            "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1543278754636",
            2,
            8,
            8,
            " The thrill of bankrupting an opponent, the possibility of playing a 9 hour game, and the absolution between winning and losing, could change with the roll of the dice. Experience the ups and downs by collecting property color’s sets to build houses, and hopefully upgrading to a hotel. But don’t play just for certain colors, or else your opponent may change their strategy.   The more properties each player owns, the more rent can be charged, but trading is where the game can help you, or hurt you. So, be wise!  Chance cards could be worth money, like \$10 for winning second place in a beauty pageant or sending you to “Go” for an extra \$200; but you might just get the one that says, “Go To Jail”.  Buy, Sell, Dream and Scheme to Win it All!  Turn a debt into an ultimate victory! ",
            "Hasbro Games",
            arrayOf("Hasbro Games"),
            1.5689655172413794,
            " ",
            "https://www.boardgameatlas.com/search/game/3IWfKb37mc/7-wonders-catan"
        ),
        GameDto(
            "5SjD0ZuSyA",
            "Monopoly: European Edition",
            "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1551364670252",
            "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1551364670252",
            2,
            12,
            8,
            " This version was released in celebration of the EU for 1992.  The player tokens are beautiful monuments from major cities in Europe.  There are 12 monuments (one for each country that was part of the EU in 1992). ECU's (Euros) are used for cash and the dice have EU stars on them instead of numbers or dots. Instead of stations there are airports located in the capitals of four 'smaller' member states, the streets are from the other eight member states. \\n\\n",
            " ",
            arrayOf(
                "Editrice Giochi",
                "Hasbro",
                "Kenner",
                "Parker Brothers",
                "Waddington's Games",
                " Inc."
            ),
            2.0,
            " ",
            "https://www.boardgameatlas.com/search/game/3IWfKb37mc/7-wonders-catan"
        ),
        GameDto(
            "OIXt3DmJU0",
            "Catan",
            "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559258096678-51Eiofu9mqL.jpg",
            "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559258096678-51Eiofu9mqL.jpg",
            3,
            4,
            10,
            " The women and men of your expedition build the first two settlements. Fortunately, the land is rich in natural resources. You build roads and new settlements that eventually become cities. Will you succeed in gaining supremacy on Catan? Barter trade dominates the scene. Some resources you have in abundance, other resources are scarce. Ore for wool, brick for lumber - you trade according to what is needed for your current building projects. Proceed strategically! If you found your settlements in the right places and skillfully trade your resources, then the odds will be in your favor. But your opponents are smart too. \\r\\n\\r\\n To begin the game, we build the game board using hexagonal terrain tiles. Catan is born - a beautiful island with mountains, pastures, hills, fields, and forests, surrounded by the sea. \\r\\n\\r\\n Each of us places two small houses on spaces where three terrain hexes meet. They are our starting settlements. \\r\\n\\r\\n And so it begins. I roll two dice. An “11”! Each terrain hex is marked with a die roll number. Each player who owns a settlement adjacent to a terrain hex marked with the number rolled receives a resource produced by this hex. Hills produce brick, forests produce lumber, mountains produce ore, fields produce grain, and pastures produce wool. \\r\\n\\r\\n We use these resources to expand across Catan: we build roads and new settlements, or we upgrade our existing settlements to cities. For example, a road costs 1 brick and 1 lumber. If we do not have the necessary resources, we can acquire them by trading with our opponents. \\r\\n\\r\\n Each settlement is worth 1 victory point and each city is worth 2 victory points. If you expand cleverly, you may be the first player to reach 10 victory points and thus win the game! ",
            "Catan Studio",
            arrayOf(
                "Catan Studio",
                "Kosmos (Germany)",
                "Filosofia (France)",
                "999 Games (Benelux)",
                "Capcom (Japan)",
                "Smart (Russia)",
                "Κάισσα (Greece)",
                "Devir (Brazil)",
                "HaKubia (Israel)",
                "Grow Jogos e Brinquedos (Brazil)",
                "Galakta (Poland)",
                "Albi (Czech republic and Slovakia)"),
            2.9179487179487182,
            "https://www.catan.com/game/catan#prof-easy",
            "https://www.boardgameatlas.com/search/game/3IWfKb37mc/7-wonders-catan"
        ),
        GameDto(
            "oGVgRSAKwX",
            "Carcassonne",
            "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254282618-61HduAZGE7L.jpg",
            "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254282618-61HduAZGE7L.jpg",
            2,
            5,
            7,
            "Each game of  Carcassonne  reveals a unique environment as tiles form a landscape of cities, roads, fields, and monasteries. Claim these features with your followers to win the game.\r\n\r\n  Carcassonne  is a tile placement game where players collectively construct the area around the medieval French city of Carcassonne while competing to place followers on various features and score the most points. First published in 2000, the game's accessible yet deep design has attracted a wide fan base and led to the development of numerous expansions and standalone titles in the  Carcassonne  line. ",
            "Z-Man Games",
            arrayOf(
                "Z-Man Games",
                "Hans im Gluck (Germany)",
                "999 Games (Netherlands)",
                "Фантасмагория (Bulgaria)",
                "Lautapelit.fi (Finland)",
                "Κάισσα (Greece)",
                "メビウスゲームズ (Japan)",
                "Giochi Uniti (Italy)",
                "Piatnik Budapest Kft. (Hungary)",
                "Grow (Brazil)",
                "Rio Grande Games (Sweden)",
                "Hobby World (Russia)"
            ),
            3.337899543378996,
            "https://images-cdn.zmangames.com/us-east-1/filer_public/d5/20/d5208d61-8583-478b-a06d-b49fc9cd7aaa/zm7810_carcassonne_rules.pdf",
            "https://www.boardgameatlas.com/search/game/3IWfKb37mc/7-wonders-catan"
        )
    )